version: '3.9'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: crocodile_user
      POSTGRES_DB: crocodile_db
      PGPORT: 5433
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"